### ISSUE TITLE
Site is not working

### ISSUE THREAD

**Issue by passick** [vikhyat/latex-to-unicode#14]
http://vikhyat.net/projects/latex_to_unicode/ does not convert formulas.

Chrome’s console says:

```
XMLHttpRequest cannot load http://app.vikhyat.net/latex_to_unicode/1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://vikhyat.net' is therefore not allowed access. The response had HTTP status code 502.
```

**Comment by vikhyat** [comment]
Should be back up now.

**Comment by passick** [comment]
Not working again =\

**Comment by vikhyat** [comment]
Thanks for the heads up, should be fixed again. The process doesn't start up automatically when the server is rebooted, I'll have to fix that.

**Comment by filipre** [comment]
Your description of the repo has the wrong url: 
http://vikhyat.net/stuff/latex_to_unicode/ gives a 404.

**Comment by vikhyat** [comment]
@filipre Thanks for the heads up, I've updated the URL.
